version: "3.7"

services:
  n8n:
    image: n8nio/n8n:1.95.3
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - WEBHOOK_TUNNEL_URL=http://152.53.84.222:5678
      - N8N_PROTOCOL=http
      - N8N_EDITOR_BASE_URL=http://152.53.84.222:5678
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
    volumes:
      - ./n8n_data:/home/node/.n8n
